# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-26 06:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Markdowm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('path', models.FileField(upload_to='upload/')),
                ('check_day', models.DateField(auto_now=True, verbose_name='检查日期')),
            ],
        ),
        migrations.CreateModel(
            name='Mindnode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('path', models.FileField(upload_to='upload/')),
                ('check_day', models.DateField(auto_now=True, verbose_name='检查日期')),
            ],
        ),
        migrations.AddField(
            model_name='markdowm',
            name='belong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markdown.Mindnode'),
        ),
    ]
