# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-26 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markdown', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markdowm',
            name='belong',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='markdown.Mindnode'),
        ),
    ]
