# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-26 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markdown', '0002_auto_20181026_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markdowm',
            name='belong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='markdown.Mindnode'),
        ),
        migrations.AlterField(
            model_name='markdowm',
            name='path',
            field=models.FileField(upload_to='md/'),
        ),
    ]
