# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-26 07:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markdown', '0003_auto_20181026_0713'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Markdowm',
            new_name='Markdown',
        ),
    ]
