# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-26 07:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markdown', '0004_auto_20181026_0721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='markdown',
            options={'ordering': ['check_day'], 'verbose_name': 'Markdown', 'verbose_name_plural': 'Markdown'},
        ),
        migrations.AlterModelOptions(
            name='mindnode',
            options={'ordering': ['check_day'], 'verbose_name': 'Mindnode', 'verbose_name_plural': 'Mindnode'},
        ),
        migrations.AlterModelTable(
            name='markdown',
            table='Markdown',
        ),
        migrations.AlterModelTable(
            name='mindnode',
            table='Mindnode',
        ),
    ]
