# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-23 09:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_author_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='picture',
            field=models.ImageField(null=True, upload_to='static/upload/usring'),
        ),
        migrations.AlterField(
            model_name='book',
            name='Publisher',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 23, 17, 10, 31, 113787)),
        ),
    ]
