# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-27 08:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20180727_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='publisher',
            field=models.ManyToManyField(null=True, to='index.Publisher'),
        ),
        migrations.AlterField(
            model_name='book',
            name='Publisher',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 27, 16, 22, 28, 954444)),
        ),
    ]
